name: QuickJS_iOS
attributes:
  CLASSPREFIX: QJS
options:
  bundleIdPrefix: com.luafan
  developmentLanguage: en
settings:
targets:
  QuickJS_iOS:
    type: library.static
    platform: iOS
    deploymentTarget: "11.0"
    scheme:
      testTargets:
        - QuickJS_iOSTests
    sources:
      - path: quickjs/quickjs.c
      - path: quickjs/cutils.c
      - path: quickjs/libbf.c
      - path: quickjs/libregexp.c
      - path: quickjs/libunicode.c
      - path: quickjs/quickjs-libc.c
      - path: quickjs/unicode_gen.c
      - path: quickjs/quickjs.h
      - path: quickjs/quickjs-libc.h
      - path: quickjs/quickjs-atom.h
      - path: QuickJS-iOS
        excludes:
    settings:
      INFOPLIST_FILE: QuickJS-iOS/Info.plist
      GCC_PREFIX_HEADER: QuickJS-iOS/PrefixHeader.pch
      OTHER_CFLAGS: $(inherited) -DCONFIG_VERSION=\"2021-03-27\"
      ENABLE_BITCODE: YES
      TARGETED_DEVICE_FAMILY: 1
      PRODUCT_BUNDLE_IDENTIFIER: com.luafan.QuickJS-iOS
  QuickJS_iOSTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "11.0"
    sources: QuickJS-iOSTests
    dependencies:
      - target: QuickJS_iOS

